Document: emqttd
Title: Debian emqttd Manual
Author: <insert document author here>
Abstract: This manual describes what emqttd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/emqttd/emqttd.sgml.gz

Format: postscript
Files: /usr/share/doc/emqttd/emqttd.ps.gz

Format: text
Files: /usr/share/doc/emqttd/emqttd.text.gz

Format: HTML
Index: /usr/share/doc/emqttd/html/index.html
Files: /usr/share/doc/emqttd/html/*.html
